### PR TITLE
Remove python-specific conda environments

### LINKED ISSUE #74: Get rid of python-version specific conda environments
We already did this in pymc: https://github.com/pymc-devs/pymc/pull/5911

### PR DESCRIPTION
**Pull request by ricardoV94**
Closes #74

### CODE REVIEW

**Comment by ferrine** [comment]
Gitpod file relies on the env file as well

**Review by twiecki — APPROVED** [review]

**Comment by ricardoV94** [comment]
The CI is failing

**Comment by ricardoV94** [comment]
@maresb Any chance you could help out here :D?

**Comment by maresb** [comment]
I'm a bit out-of-the-loop here with the exact context...

But 3.7 is failing because it's no longer supported. (We're now at >=3.8 for all the main packages.) Perhaps it should be bumped to 3.8?

The 3.10 failure looks numerical, perhaps the thresholds need to be adjusted? (Or switch from absolute to relative error or something of the sort?)

**Comment by ricardoV94** [comment]
Probably screwed up something with the blackjax optional dependency

**Comment by ricardoV94** [comment]
Hmm... I also see it in this other PR: https://github.com/pymc-devs/pymcx/actions/runs/3468481561/jobs/5794341223

So not my fault?

**Pull request merged**
